### ISSUE TITLE
List item in markdown with checkbox is not correctly indented

### ISSUE THREAD

**Issue by isodude** [mattermost/mattermost#22550]
#### Summary
List item in markdown with checkbox is not correctly indented

#### Steps to reproduce
In chat, type
```
- list-item
- [ ] list-item
- list-item
```

#### Expected behavior
- list-item
- [x] list-item
- list-item

Note here that the dot is replaced by the checkbox.

#### Observed behavior (that appears unintentional) 
- list-item
  :white_square_button: list-item
- list-item

Note here that the list item is indented as a list item but the checkbox is included in the list-item and does not replace the dot in itself.

#### Note
It seems that https://github.com/mattermost/mattermost-server/commit/355056622b3bd1cd6e1f3dda18273a473bc14823 fixes this last time around.
My fix this to make it like how github do it is to add
```css
li.list-item--task-list {
  margin-left: -15px;
}
```
As I go through that I see that even github misaligns the list!
Since the dot is much smaller than the checkbox, the checkbox will push the list-time text to the right.
```css
ul.markdown__list li.not(list-item--task-list) span {
  margin-left: 2px;
}
```
Fixes this somewhat.

- - [ ] list-item

ends up with a linebreak between the dot and the checkbox.
If I remove the span inside
```
<ul class="markdown__list">
::marker
<span><ul class="markdown__list"><ul></span>
</ul>
```

It behaves better.
