### ISSUE TITLE
Failure to establish SSL connection to remote Postgresql

### ISSUE THREAD

**Issue by tka85** [mattermost/mattermost#24411]
#### Summary
Running self-hosted MM in docker. Should connect to remote Postgresql with SSL. The driver name and driver source are set correctly for Postgresql in docker-compose, pg_hba.conf is setup correctly, Pg has valid letsencrypt certs.

#### Steps to reproduce
User external Nginx as rev proxy with letsencrypt certs and create service for MM in a docker-compose:

```
mattermost:
    container_name: mattermost
    image: mattermost/mattermost-enterprise-edition:7.8
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - mattermost-vol:/mattermost/
    environment:
      - TZ=UTC
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://${MM_DB_USER}:${MM_DB_PASS}@${MM_DB_HOST}:${MM_DB_PORT}/${MM_DB_NAME}?ssl=true&sslmode=require
    expose:
      - 8065

volumes:
    mattermost-vol:
```

Create in remote Postgresql (1) user `mattermost` (2) database `mattermost_db` owned by user `mm` and grant all privs to him on this db. Setup `pg_hba.conf` to accept connection only from host where MM docker is running and only with method `hostssl`:

```
hostssl    all    all    xxx.xxx.xxx.xxx/32    scram-sha-256
```

#### Expected behavior

MM should be able to connect to remote Pg and initialize db for first run.

#### Observed behavior (that appears unintentional) 

Docker logs of the mattermost container:

```
{"timestamp":"2023-08-29 13:23:41.465 Z","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:242","database":"master","dataSource":"postgres://%2A%2A%2A%2A:%2A%2A%2A%2A@mydomain.com:5432/mattermost_db?ssl=true&sslmode=require"}
{"timestamp":"2023-08-29 13:23:42.118 Z","level":"error","msg":"Failed to ping DB","caller":"sqlstore/store.go:252","error":"pq: parameter \"ssl\" cannot be changed now","retrying in seconds":10}
```
and on Postgresql side logs:

```
2023-08-29 13:24:37.129 UTC [296935]: [1-1] user=[unknown],db=[unknown] LOG:  connection received: host=xxx.xxx.xxx.xxx port=36746
2023-08-29 13:24:37.581 UTC [296935]: [2-1] user=mattermost,db=mattermost_db LOG:  connection authenticated: identity="mattermost" method=scram-sha-256 (/var/lib/postgresql/data/pg_hba.conf:101)
2023-08-29 13:24:37.581 UTC [296935]: [3-1] user=mattermost,db=mattermost_db LOG:  connection authorized: user=mattermost database=mattermost_db SSL enabled (protocol=TLSv1.3, cipher=TLS_AES_256_GCM_SHA384, bits
=256)
2023-08-29 13:24:37.583 UTC [296935]: [4-1] user=mattermost,db=mattermost_db FATAL:  parameter "ssl" cannot be changed now
```

#### Possible fixes

It seems that somewhere before I make the connection shown in the logs, MM has already been told that it should run without SSL for the db connection.

Postgresql has valid letsencrypt certs.
I can confirm I can connect with psql from the MM container's host to the remote host running Postgresql using all the `$MM_DB_*` env variables used in the docker-compose's `MM_SQLSETTINGS_DATASOURCE` env variable.
