### ISSUE TITLE
Too Many Redirects when logging in from Mobile Apps when Server is using subpath hosting

### ISSUE THREAD

**Issue by wech71** [mattermost/mattermost#26894]
#### Summary
Too Many Redirects when logging in from Mobile Apps when Server is using subpath hosting. Tested in 9.7.1 and with 9.7.2

#### Steps to reproduce
* Configure Mattermost Server to use subpath hosting (like https://mattermostserver/chat)
* Ensure Android App or iOS App is logged out
* Try to Connect to the server (I used gitlab authentication, but never got threre)

#### Expected behavior
Connection Form should disappear and Login form should be displayed

#### Observed behavior (that appears unintentional) 
An error is being displayed "Too many redirects (21)"

According the nginx logs a HEAD request proxied to http://mattermost/chat, which gets redirected to http://mattermost/chat/chat then to http://mattermost/chat/chat then to http://mattermost/chat/chat/

The same can be reproduced using curl:

```
curl -L -I http://mattermost-server:8065/chat/
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /chat/chat
Vary: Origin
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 100
X-Ratelimit-Reset: 1
Date: Fri, 26 Apr 2024 10:31:03 GMT

HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /chat/chat/chat
Vary: Origin
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 99
X-Ratelimit-Reset: 1
Date: Fri, 26 Apr 2024 10:31:03 GMT

HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /chat/chat/chat/chat
Vary: Origin
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 98
X-Ratelimit-Reset: 1
Date: Fri, 26 Apr 2024 10:31:03 GMT

HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /chat/chat/chat/chat/chat
Vary: Origin
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 97
X-Ratelimit-Reset: 1
Date: Fri, 26 Apr 2024 10:31:03 GMT
...

HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat
Vary: Origin
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 50
X-Ratelimit-Reset: 6
Date: Fri, 26 Apr 2024 10:31:03 GMT

curl: (47) Maximum (50) redirects followed
```

The problem also occurs when starting with http://mattermost/chat/

The problem does not occur when using a GET Request like `curl http://mattermost/chat`.  In this case the main html is correctly being retured.

#### Possible fixes

Ensure the HEAD request does no endless redirects to the subpath even when already on the subpath.

**Comment by wech71** [comment]
> I had the same problem. I added
> 
> ```
>  if ($request_method = HEAD) {
>         return 200;
>     }

Nice. My workaround ist very similar, I only returning 405 (Method not allowed) instead of 200 (OK)

But thanks for adding - I forgot to mention the workaround :-)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-58042

**Comment by tchellomello** [comment]
Hitting the same issue with Istio + Envoy

```yaml
$ curl -v -XHEAD https://mattermost.example.com/chat/ -L
> HEAD /chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat HTTP/2
> Host: mattermost.example.com
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/2 302 
< content-type: text/html; charset=utf-8
< location: /chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat
< date: Mon, 06 May 2024 06:02:56 GMT
< x-envoy-upstream-service-time: 0
< server: mattermost.example.com
< vary: Accept-Encoding
< 
* Ignoring the response-body
* Connection #0 to host mattermost.example.com left intact
* Maximum (50) redirects followed
curl: (47) Maximum (50) redirects followed
```

However the problem does not happen whenever using a browser with a regular GET

**Comment by tchellomello** [comment]
Workaround the issue by creating this `EnvoyFilter`

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: workaround-issue-26894
spec:
  workloadSelector:
    labels:
      istio.io/gateway-name: public-gateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                if request_handle:headers():get(":method") == "HEAD" then
                  local path = request_handle:headers():get(":path")
                  if path and string.sub(path, 1, 5) == "/chat" then
                    request_handle:respond({[":status"] = "200"})
                    return
                  end
                end
              end
```
