### ISSUE TITLE
The server was deployed in a Kubernetes using an mattermost-operator and installation, but a 404 error is occurring.

### ISSUE THREAD

**Issue by finda-yeongjo** [mattermost/mattermost#27101]
#### Summary
The server was deployed in a Kubernetes using an mattermost-operator and installation, but a 404 error is occurring.

#### Steps to reproduce

1. Deploy mattermost-operator in AWS EKS (1.29)
2. deploy mattermost-installation with gitops(app of apps), argocd
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-operator
  namespace: test
spec:
  project: test

  destination:
    server: https://kubernetes.default.svc
    namespace: mattermost-operator

  source:
    repoURL: https://helm.mattermost.com
    targetRevision: 1.0.1
    chart: mattermost-operator
    helm:
      values: |
        mattermostOperator:
          enabled: true
          replicas: 1
          rbac:
            create: true
          serviceAccount:
            create: true
          env:
            maxReconcilingInstallations: 20
            maxReconcilingConcurrency: 10
            requeuOnLimitDelay: 20s
          image:
            repository: mattermost/mattermost-operator
            tag: v1.21.0
            pullPolicy: IfNotPresent
          args:
            - --enable-leader-election
            - --metrics-addr=0.0.0.0:8383

          ## Specify image pull secret for private repository
          privateRegistry:
            enabled: false
```

```
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: finda-mattermost 
  namespace: mattermost
spec:
  image: mattermost/mattermost-team-edition 
  imagePullPolicy: Always
  version: latest
  size: 1000users
  awsLoadBalancerController:
    enabled: true
    hosts: 
      - hostName: 'SOMETHING_YOUR_HOSTNAME'
    annotations:
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/load-balancer-name: SOMETHING_YOURS
      alb.ingress.kubernetes.io/group.name: SOMETHING_YOURS
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/backend-protocol: HTTP
    certificateARN: SOMETHING_YOURS
    internetFacing: false
    ingressClassName: 'alb'
  mattermostEnv: 
    - name: MM_FILESETTINGS_AMAZONS3SSE
      value: "true"
    - name: MM_FILESETTINGS_AMAZONS3SSL
      value: "true"
  # licenseSecret: ""
  database:
    external:
      secret: db-secret
  fileStore:
    external:
      url: s3.amazonaws.com
      bucket: SOMETHING_YOUR_BUCKET
      secret: bucket-secret
  # elasticSearch:
  #   host: "" 
  #   username: ""
  #   password: "" 
#  volumeMounts: {}
#  volumes: {}
#  replicas: 1 according to it.
  # scheduling:
  #   resources: {} 
  #   nodeSelector: {}
  #   affinity: {}
```

#### Expected behavior
Deploy successful

#### Observed behavior (that appears unintentional) 
1. Pod deploy success and health check success
<img width="771" alt="스크린샷 2024-05-22 오후 5 56 15" src="https://github.com/mattermost/mattermost/assets/136681927/15492379-a63f-4995-9d49-ef277cf98e13">

2. There is no error logs
<img width="1870" alt="스크린샷 2024-05-22 오후 5 58 11" src="https://github.com/mattermost/mattermost/assets/136681927/6a819695-44ed-4c1a-9bf2-4a09d110e556">

3.When accessing via the URL, a 404 error occurs.
<img width="1720" alt="스크린샷 2024-05-22 오후 5 58 57" src="https://github.com/mattermost/mattermost/assets/136681927/25982d0e-d0b1-4967-9d27-62f24e68e6b3">

<img width="700" alt="스크린샷 2024-05-22 오후 6 00 46" src="https://github.com/mattermost/mattermost/assets/136681927/8f8a872e-9414-4070-b353-3aa1bac2a272">
<img width="702" alt="스크린샷 2024-05-22 오후 6 01 33" src="https://github.com/mattermost/mattermost/assets/136681927/3767f562-43a9-4331-b62a-01ff74ae8dd4">

#### Possible fixes
Since we are using the Mattermost container image, it is difficult to identify the issue at the code level.
