### ISSUE TITLE
[Bug]: Not possible to disable Mattermost Copilot in config.json

### ISSUE THREAD

**Issue by johanhammar** [mattermost/mattermost#30946]
### Before you file a bug report

- [x] I have checked the [issue tracker](https://github.com/mattermost/mattermost/issues) and have not found an issue that matches the one I'm filing.
- [x] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [x] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.uservoice.com/forums/306457-general/.
- [x] This issue reproduces on one of the [currently supported server versions](https://docs.mattermost.com/about/mattermost-server-releases.html#latest-releases).
- [x] I have read the [contribution guidelines](https://github.com/mattermost/mattermost/blob/master/CONTRIBUTING.md) and the [Mattermost Handbook Contribution Guidelines](https://handbook.mattermost.com/contributors/contributors/guidelines/contribution-guidelines).

### Mattermost Server Version

10.5.4

### Operating System

Linux

### Steps to reproduce

Hi!

It seems it is not possible to disable Mattermost Copilot in config.json, however it is possible in the System Console.

Like other plugins I try to disable it like this:

```
"PluginStates": {
      "com.mattermost.calls": {
        "Enable": false
      },

      ....

     "mattermost-ai": {
        "Enable": false
      }
    }
```

With the mattermost-ai configuration in config.json Mattermost fails to start

I couldn't find any documentation regarding configuration of Copilot in config.json

Is it a bug or not supported (yet)?

### Expected behavior

It should be possible to disable Copilot in config.json like other plugins

### Observed behavior

Mattermost fails to start when disabling Copilot in config.json

### Log Output

```shell

```

**Comment by iva-5-middleware** [comment]
That's interesting. We also use v10.5.4, but the following config works for us:

```yml
        "PluginStates": {
            "com.mattermost.calls": {
                "Enable": true
            },
            "com.mattermost.custom-attributes": {
                "Enable": true
            },
(...)
            "mattermost-ai": {
                "Enable": false
            },
(...)
```

What does the log say why the service crashes during start?
